from enum import StrEnum


class SessionStatus(StrEnum):
    CREATED = "CREATED"
    DOCUMENT_REQUIRED = "DOCUMENT_REQUIRED"
    DOCUMENT_PROCESSING = "DOCUMENT_PROCESSING"
    SELFIE_REQUIRED = "SELFIE_REQUIRED"
    LIVENESS_REQUIRED = "LIVENESS_REQUIRED"
    NFC_REQUIRED = "NFC_REQUIRED"
    PROCESSING = "PROCESSING"
    MANUAL_REVIEW = "MANUAL_REVIEW"
    VERIFIED = "VERIFIED"
    REJECTED = "REJECTED"
    EXPIRED = "EXPIRED"


class VerificationLevel(StrEnum):
    DOCUMENT_ONLY = "DOCUMENT_ONLY"
    DOCUMENT_FACE = "DOCUMENT_FACE"
    DOCUMENT_FACE_LIVENESS = "DOCUMENT_FACE_LIVENESS"
    DOCUMENT_FACE_LIVENESS_NFC = "DOCUMENT_FACE_LIVENESS_NFC"


class DocumentType(StrEnum):
    KH_NATIONAL_ID = "KH_NATIONAL_ID"
    KH_PASSPORT = "KH_PASSPORT"
    KH_NSSF = "KH_NSSF"
    PASSPORT = "PASSPORT"
    NATIONAL_ID = "NATIONAL_ID"
    RESIDENCE_CARD = "RESIDENCE_CARD"
    DRIVING_LICENSE = "DRIVING_LICENSE"
    UNKNOWN = "UNKNOWN"


class CheckResult(StrEnum):
    PASS = "PASS"
    REVIEW = "REVIEW"
    FAIL = "FAIL"
    NOT_APPLICABLE = "NOT_APPLICABLE"
    UNAVAILABLE = "UNAVAILABLE"


class RiskDecision(StrEnum):
    PASS = "PASS"
    REVIEW = "REVIEW"
    FAIL = "FAIL"


class ReviewAction(StrEnum):
    APPROVE = "APPROVE"
    REJECT = "REJECT"
    REQUEST_RECAPTURE = "REQUEST_RECAPTURE"


class NFCStatus(StrEnum):
    NFC_NOT_SUPPORTED = "NFC_NOT_SUPPORTED"
    NFC_NOT_AVAILABLE = "NFC_NOT_AVAILABLE"
    NFC_FAILED = "NFC_FAILED"
    NFC_READ = "NFC_READ"
    NFC_VERIFIED = "NFC_VERIFIED"
