#!/usr/bin/env python3
"""Write the KYC production readiness report (JSON and Markdown) from src/kyc/readiness.py.

The overall result is computed from the component matrix: READY only when every critical
component is PRODUCTION_READY. Run it after any change that adds evidence, and commit the
output so the approval history is reviewable.

    python scripts/readiness_report.py -o docs/readiness
"""

import argparse
import json
from pathlib import Path
import sys

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

from kyc.readiness import BLOCKING, COMPONENTS, classify, report  # noqa: E402


def markdown(data: dict) -> str:
    lines = ["# KYC Production Readiness Report", "", f"**Overall: {data['overall']}**", "",
             "READY requires every critical component to be PRODUCTION_READY. This report is generated by "
             "`scripts/readiness_report.py` from `src/kyc/readiness.py`.", ""]
    if data["blockers"]:
        lines += ["## Critical blockers", ""]
        lines += [f"- **{item['component']}**: {item['blocker']}" for item in data["blockers"]]
        lines.append("")
    lines += ["## Approval matrix", "",
              "| Component | Critical | Status | Implemented | Automated tests | Real tested | Calibrated | Security reviewed | Next action |",
              "|---|---|---|---|---|---|---|---|---|"]
    for item in COMPONENTS:
        lines.append(f"| {item.name} | {'yes' if item.critical else 'no'} | {item.status} | {item.implemented} | "
                     f"{item.automated_tests} | {item.real_tested} | {item.calibrated} | {item.security_reviewed} | "
                     f"{item.next_action} |")
    lines += ["", "## Evidence and limitations", ""]
    for item in COMPONENTS:
        lines.append(f"### {item.name}")
        lines.append("")
        lines.append(item.evidence)
        for limitation in item.limitations:
            lines.append(f"- Limitation: {limitation}")
        lines.append("")
    non_blocking = [item.name for item in COMPONENTS if not item.critical and item.status in BLOCKING]
    if non_blocking:
        lines += ["## Non-critical gaps (allowed under READY_WITH_LIMITATIONS)", "", ", ".join(non_blocking), ""]
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("-o", "--output", type=Path, default=Path("docs/readiness"))
    args = parser.parse_args()
    data = report()
    args.output.mkdir(parents=True, exist_ok=True)
    (args.output / "readiness.json").write_text(json.dumps(data, indent=2) + "\n")
    (args.output / "READINESS.md").write_text(markdown(data))
    print(f"{classify()}: {len(data['blockers'])} critical blockers; written to {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
